# Generated by Django 4.0.6 on 2022-08-02 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_alter_bookslike_username_alter_comment_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslike',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_like', to='books.book'),
        ),
        migrations.AlterField(
            model_name='bookslike',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
